blogsproject/blogs/urls.py
from django.urls import path, re_path
from blogs.views import PostLV, PostDV, PostAV, PostMAV, PostDAV, PostTAV, PostYAV, TagCloudTV, TaggedObjectLV, create_comment, delete_comment, create_recomment, delete_recomment, SearchFormView, PostCreateView, PostChangeLV, PostUpdateView, PostDeleteView, LikeView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blogs'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<str:slug>/', PostDV.as_view(), name='post_detail'),
     # re_path(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # 댓글
    path('create_comment/<int:post_id>/<str:slug>/', create_comment, name='create_comment'),
    path('delete_comment/<int:comment_id>/<str:slug>', delete_comment, name='delete_comment'),
    # 대댓글
    path('create_recomment/<int:comment_id>/<str:slug>/', create_recomment, name='create_recomment'),
    path('delete_recomment/<int:recomment_id>/<str:slug>/', delete_recomment, name='delete_recomment'),
    
    # archive
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # tag
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),

    # search
    path('search/', SearchFormView.as_view(), name='search'),

    # CRUD
    path('add/', PostCreateView, name='add'),
    path('change/', PostChangeLV, name='change'),
    path('<int:post_pk>/update/', PostUpdateView, name='update'),
    path('<int:post_pk>/delete/', PostDeleteView, name='delete'),

    # Likes
    path('likes/<int:post_id>/<str:slug>/', LikeView, name='likes'),
    # path('likes', LikeView, name='likes')
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogsproject/blogsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from django.conf import settings
from django.conf.urls.static import static
# UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blogs/', include("blogs.urls")),
    path('accounts/', include("accounts.urls")),
    # 인증
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/register/', UserCreateView.as_view(), name='register'),
    # path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# debug_toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ]

blogsproject/blogs/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify
from accounts.models import BlogUser

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    # verbose_name? -> 별칭 붙여준 것!
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    # SlugField? -> 각 게시글의 tag같은 느낌! URL에서 pk 대신 이해하기 쉽게 사용
    # unique=True 통해 고유의 검색 시 기본 키 대신 사용할 수 O
    # allow_unicode=True 통해 한글 처리 O
    # help_text -> form에서 해당 칼럼 설명해주는 문구로 나타남(Admin에서 확인O)
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('content')
    create_dt = models.DateField('CREATE DATE', auto_now_add=True)
    # auto_now_add=True -> 객체 생성 시간(작성)을 자동으로 기록
    modify_dt = models.DateField('MODIFY DATE', auto_now=True)
    # auto_now -> 객체 저장 시간(변경)을 자동으로 기록
    tags = TaggableManager(blank=True)
    # TaggableManager? -> taggit앱 내에서 정의된 클래스. Tags란 별칭과 null=True항목 default
    # taggit패키지에는 자체 테이블 정의O! -> 데이터베이스에 Tag, TaggedItem이라는 테이블 자동 추가
    owner = models.ForeignKey(BlogUser, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)
    image = models.ImageField(null=True, blank=True)
    likes = models.ManyToManyField(BlogUser, blank=True, related_name='좋아요')

    class Meta:
        # 필드 속성 외에 필요한 파라미터 -> Mete내부 클래스로 정의!
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        # 복수 별칭
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)
        # ordering -> 정렬! modify_dt 컬럼을 기준으로 내림차순으로

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.CharField('내용', max_length=200)
    created_dt = models.DateField(auto_now = True)

class ReComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    body = models.CharField('대댓글내용', max_length=100, null=True)
    created_dt = models.DateField(auto_now = True)

# Create your models here.

blogsproject/blogs/forms.py
from django import forms
from .models import Comment, Post, ReComment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body',]

class ReCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment
        fields = ['body',]

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search_word')

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'content', 'image',] 

blogsproject/blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from blogs.models import Post, Comment, ReComment
from blogs.forms import CommentForm, PostSearchForm, PostCreateForm, ReCommentForm
from django.db.models import Q
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
# from blogsproject.views import OwnerOnlyMixin
from django.contrib.auth.decorators import login_required
from accounts.models import BlogUser

from django.http import HttpResponse
import json

# ListView
class PostLV(ListView):
    model = Post
    template_name = 'post_all.html'
    # 지정 안해주면 default로 blogs
    context_object_name = 'posts'
    # default인 object name 말고 사용자 지정 가능
    paginate_by = 2
    # 한 페이지에 2개 보여줌 / paginate_by 통해 django 페이지 기능 사용 O

# DetailView
class PostDV(DetailView):
    model = Post
    template_name = 'post_detail.html'
    # context_object_name = 'my_post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['commentform'] = CommentForm()
        context['recommentform'] = ReCommentForm()
        return context

# ArchiveView
# -> 테이블로부터 객체 리스트를 가져와, 날짜 필드를 기준으로 최신 객체를 출력
# 역시 default html 이름 존재
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'
    template_name = 'post_archive.html'
    # 기준이 되는 날짜 필드를 modify_dt로 지정(변경 날짜가 최근인 녀석을 먼저 출력)

class PostYAV(YearArchiveView):
    # YearArchiveView -> 테이블로부터 날짜 필드의 연도를 기준으로 가져와, 객체들이 속한 월을 출력
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    template_name = 'post_archive_year.html'
    # True -> 해당 연도에 해당하는 객체 리스트를 만들어 템플릿에 넘겨줌!
    # 즉 html에서 object_list 변수 사용할 수 O

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = 'post_archive_month.html'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = 'post_archive_day.html'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = 'post_archive_day.html'

# TAG
class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'
    # 이걸로 tag를 어떻게 띄워준다야?
    # -> taggit_cloud.html에서 {%get_tagcloud%}를 통해 클라우드 처리!

class TaggedObjectLV(ListView):
    # 특정 tag가 달려있는 Post들의 list 보여주는 함수
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # super()왜 쓰냐? -> 밑에서 새로 정의해줄텐데, 그 전 원래 상태의 상위 context를 호출한 것!
        context['tagname'] = self.kwargs['tag']
        # self.kwargs['tag'] <- url을 통해 넘어오는 값을 추출할 때 사용!
        # 즉 url에서 tag 파라미터로 넘어온 값을 context에 담음
        return context


# 댓글

# class Create_Comment(CreateView):
#     model = Comment
#     fields = ('title', 'description')
#     template_name = 'post_detail.html'
#     success_url = '/'
#     form_class = CommentForm

def create_comment(request,post_id,slug):
    filled_form = CommentForm(request.POST) 

    if filled_form.is_valid():    
        temp_form = filled_form.save(commit=False)         
        temp_form.post = Post.objects.get(id = post_id) 
        filled_form.save()  
    
    return redirect('blogs:post_detail', slug)

def delete_comment(request,comment_id,slug):
    remove_comment = Comment.objects.get(pk=comment_id)
    remove_comment.delete()
    return redirect('blogs:post_detail', slug)
  
def create_recomment(request,comment_id, slug):
    filled_form = ReCommentForm(request.POST)
    if filled_form.is_valid():
        temp_form = filled_form.save(commit=False)
        temp_form.comment = Comment.objects.get(pk=comment_id)
        temp_form.save()
    return redirect('blogs:post_detail', slug)

def delete_recomment(request,recomment_id, slug):
    remove_recomment = ReComment.objects.get(pk=recomment_id)
    remove_recomment.delete()
    return redirect('blogs:post_detail', slug)

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'post_search.html'

    # form_valid <- 유효성 검사 실시! 에러 없으면 실행
    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        # 유효성 검사 통과시, 사용자가 입력한 값은 cleaned_data 라는 사전에 존재
        # 이 사전에서 search_word(이용자가 form에서 입력한 값)를 추출해 searchWord 란 이름으로 저장!

        post_list = Post.objects.filter(Q(title__icontains=searchWord)|Q(description__icontains=searchWord)
        |Q(content__icontains=searchWord)).distinct()

        context = {}
        # context 변수를 dic 형태로!

        context['form'] = form
        # form 객체, 즉 여기서는 PostSearchForm을 넘겨주자

        context['search_term'] = searchWord
        # 검색용 단어인 searchWord도 넘겨주기
        context['object_list'] = post_list
        # 검색 결과 리스트인 post_list도 넘겨주기

        return render(self.request, self.template_name, context)
        # form_valid 메소드는 보통 HttpResponseRedirect 객체를 반환한다.
        # 여기서는 form_valid 메소드를 재정의하여 render함수를 사용! -> HttpResponse 객체를 반환했다!

@login_required
# C
def PostCreateView(request):
    if request.method == "POST":
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.owner = request.user
            form.save()
            return redirect('blogs:index')
    form = PostCreateForm()
    return render(request, 'post_form.html', {'form' : form})

@login_required
# R
def PostChangeLV(request):
    post = Post.objects.all()
    context = {'post' : post}
    return render(request, 'post_change_list.html', context)

# U
def PostUpdateView(request, post_pk):
    my_post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = PostCreateForm(request.POST, instance=my_post)
        if form.is_valid():
            form.save()
            return redirect('blogs:change')
    form = PostCreateForm(instance = my_post)
    return render(request, 'post_form.html', {'form' : form})

# D
def PostDeleteView(request, post_pk):
    my_post = Post.objects.get(pk=post_pk)
    my_post.delete()
    return redirect('blogs:change')

# like
def LikeView(request, post_id, slug):
    user = request.user
    if request.method == "POST" and user.is_authenticated:
        mylike = Post.objects.get(pk=post_id)

        if mylike.likes.filter(id = user.id).exists():
            mylike.likes.remove(user)
        else :
            mylike.likes.add(user)
    else :
        return redirect('accounts:login')
    return redirect('blogs:post_detail', slug)

# Create your views here.

blogsproject/blogs/templates/post_all.html
{% extends 'home.html' %}

{%block title%}post_all{%endblock%}
{% block content %}
{% load static %}
{%block extrahead%}{{block.super}}<link rel="stylesheet" href="{% static 'css/post_all.css' %}">{%endblock%}
    <img src="{% static 'image/Charlie_Brown.png' %}" class="main-img">
    
    <h1>Blog List</h1><br>
    <b><a href="{% url 'blogs:search' %}">Search_page</a></b>
    <br><br>

    {% for post in posts %}
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    <!-- <a href="{% url 'blogs:post_detail' post.id %}">{{post.title}}</a> -->
    <!-- get_absolute_url() -> models에서 정의! - /blog/post/slug단어/ 형태로 url!! -->
    {{post.modify_dt|date:"N d, Y"}}
    <!-- modify_dt 속성값을 N d, Y 형식으로 출력 -->
    <p>{{post.description}}</p>
    {% endfor %}
    <br>

    <!-- 페이징 기능 -->
    <div>
        <span>
            {% if page_obj.has_previous %}
            <!-- page_obj -> django의 Page 객체가 들어있는 context변수(즉 default) -->
            <!-- page_obj.has_previous -> 현 페이지 기준 이전 페이지 있는지 확인하는 것! -->
                <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
                <!-- {{ page_obj.previous_page_number }} -> 이전 페이지 번호 -->
                <!-- 즉 href링크는 ?page=이전 페이지 번호 형태! -->
            {% endif %}

            Page {{ page_obj.number }} of {{page_obj.paginator.num_pages}}
            <!-- {{ page_obj.number }} -> 현재 페이지 번호 -->
            <!-- {{ page_obj.paginator.num_pages }} -> 전체 페이지 번호 -->

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
                <!-- page_obj.next_page_number -> 다음 페이지 번호 -->
            {% endif %}
        </span>
    </div>
{%endblock%}

blogsproject/blogs/templates/post_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Post Archives until {% now "N d, Y" %}</h1>
    <!-- { now } -> 현재 날짜, 시간을 원하는 형태로 출력 -->
    <ul>
        {% for date in date_list %}
            <!-- date_list -> DateQuerySet의 객체 리스트(datetime,date타입)를 담고 있는 context변수 -->
        <li style="display: inline;">
            <a href="{% url 'blogs:post_year_archive' date|date:'Y' %}">Year{{date|date:"Y"}}</a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{post.get_abolute_url}}">{{post.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blogsproject/blogs/templates/post_archive_day.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Post Archives for {{day|date:"N d Y"}}</h1>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;</li>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blogsproject/blogs/templates/post_archive_month.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Post Archives for {{month|date:"N, Y"}}</h1>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;</li>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blogsproject/blogs/templates/post_archive_year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Post Archives for {{year|date:"N Y"}}</h1>
    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blogs:post_month_archive' year|date:'Y' date|date:'b' %}">
                {{ date|date:"F"}}
            </a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">{{post.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
    
    

</body>
</html>

blogsproject/blogs/templates/post_change_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Post Change - {{user}}</h1>
    {% for item in post %}
        {% if item.owner == request.user %}
            {{item.title}}
            {{item.owner}}
            <a href="{% url 'blogs:update' item.id %}">Update</a>
            <a href="{% url 'blogs:delete' item.id %}">Delete</a><br>
        {% endif %}
    {% endfor %}    
{% endblock %}

blogsproject/blogs/templates/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Post Delete</h1>
    <form action="." method="POST">
        {%csrf_token%}
        Want to delete {{object}}?
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

blogsproject/blogs/templates/post_detail.html
{% extends 'home.html' %}

{%block title%}post_detail{%endblock%}
{% block content %}
{% load static %}
{%block extrahead%}
    {{block.super}}
    <!-- <link rel="stylesheet" href="{% static 'css/post_detail.css' %}"> -->
    <script src = "{% static 'post_detail.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}
    <h2>{{object.title}}</h2>
    <p>
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previoust post?">
            &laquo;-- {{ object.get_previous }}
            <!-- &laquo; -> html특수문자 -->
        </a>

        {% else %}
        no page

        {% endif %}

        📄📌
        
        {% if object.get_next %}
        <a href="{{ object.get_next.get_absolute_url }}" title="View next post?">
            {{ object.get_next }} --&raquo;
            <!-- &laquo; -> html특수문자 -->
        </a>
        {% else %}
        no page

        {% endif %}
    </p>
    
    <!-- post_detail -->
    <p>{{ object.modify_dt|date:"j F Y" }}</p>
    <br>
    <div class="mypost">
        {{ object.content|linebreaks}}
        <!-- |linebreaks -> 새로운 line을 인식하게 함 -->
        <div class="main-img">
        {% if object.image %}
        <img src="{{object.image.url}}" style="width: 200px; height: 200px;">
        {% endif %}

        <form method="POST" action="{% url 'blogs:likes' object.id object.slug%}">
            {% csrf_token %}
            <input type="submit" value="좋아요">
        </form>
        {{object.likes.count}}
        <hr>
    </div>
 


    <!-- Comment -->
    <div>
        <form method="POST" action="{% url 'blogs:create_comment' object.id object.slug %}">
            {%csrf_token%}
            {{commentform}}
            <input type="submit" value="작성">
        </form>
        {% for comments in object.comment_set.all %}
        <span>comments : {{comments.body}}
            <a href="{% url 'blogs:delete_comment' comments.id object.slug%}">삭제</a>
            {% for recomments in comments.recomment_set.all %}
            <br>recomments : {{recomments.body}}
            {% endfor %}
            <form method="POST" action="{% url 'blogs:create_recomment' comments.id object.slug %}">
                {%csrf_token%}
                {{recommentform}}
                <input type="submit" value="작성">
            </form>
        </span><br>
        {% endfor %}
    </div>

    <!-- TAG -->
    <div>
        <b>TAGS</b><i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        <!-- taggit_templatetags2 <- 요 패키지에 정의된 커스텀 태그 이용 위해 호출!-->
        {% get_tags_for_object object as "tags" %}
        <!-- 요놈이 그 커스텀 태그! object 객체(view에서 보내준 Post모델)
            에 달려 있는 태그들의 리스트 추출 -> 이를 tags로 정의해 html에서 사용-->
        {% for tag in tags %}
        <a href="{% url 'blogs:tagged_object_list' tag.name %}">{{tag.name}}</a>
        <!-- .name은 어디에? -> taggit 패키지-Tag 테이블에! -->
        {% endfor %} 
        &emsp;
        <a href="{% url 'blogs:tag_cloud' %}"><span>TAGCLOUD</span></a>
    </div>

    

{%endblock%}

blogsproject/blogs/templates/post_form.html
{% extends "base.html" %}

{% block content %}
    <h1>Post Create/Update = {{user}}</h1>
    {% if form.errors %}
    {{form.errors}}
    {% endif %}

    <form action="." method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <span>title : {{form.title}}</span><br>
        <span>description : {{form.description}}</span><br>
        <span>content : {{form.content}}</span>
        <span>image : {{form.image}}</span>
        <input type="submit" value="Submit">
    </form>


{% endblock %}

blogsproject/blogs/templates/post_search.html
{% extends 'base.html' %}

{%block title%}post_search{%endblock%}

{% block content %}
<h1>blog search</h1>
<form action="." method="POST">
    {%csrf_token%}
    {{form}}
    <input type='submit' value="Submit">
</form>
<br>
{% if object_list %}
    {% for post in object_list %}
    <a href='{{post.get_absolute_url}}'>{{post.title}}</a>
    {{post.modify_dt}}
    {{post.description}}
    {% endfor %}

{% elif search_term %}
<!-- object_list가 없는 경우 -> 그럼 검색은 했는지-> 검색 단어를 입력했는지 여부 판단 -->
    <b>Search_Word({{search_term}})Not Found</b>

{% endif %}

{% endblock %}