blogsproject/accounts/urls.py
from django.urls import path
from .views import LoginView, RegisterView, LogoutView, passwordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView, name = 'login'),
    path('register/', RegisterView, name = 'register'),
    path('logout/', LogoutView, name='logout'),
    path('passwordchange/', passwordChangeView, name='password_change'),
]

blogsproject/blogs/urls.py
from django.urls import path, re_path
from blogs.views import PostLV, PostDV, PostAV, PostMAV, PostDAV, PostTAV, PostYAV, TagCloudTV, TaggedObjectLV, create_comment, delete_comment, create_recomment, delete_recomment, SearchFormView, PostCreateView, PostChangeLV, PostUpdateView, PostDeleteView, LikeView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blogs'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<str:slug>/', PostDV.as_view(), name='post_detail'),
     # re_path(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # 댓글
    path('create_comment/<int:post_id>/<str:slug>/', create_comment, name='create_comment'),
    path('delete_comment/<int:comment_id>/<str:slug>', delete_comment, name='delete_comment'),
    # 대댓글
    path('create_recomment/<int:comment_id>/<str:slug>/', create_recomment, name='create_recomment'),
    path('delete_recomment/<int:recomment_id>/<str:slug>/', delete_recomment, name='delete_recomment'),
    
    # archive
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # tag
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),

    # search
    path('search/', SearchFormView.as_view(), name='search'),

    # CRUD
    path('add/', PostCreateView, name='add'),
    path('change/', PostChangeLV, name='change'),
    path('<int:post_pk>/update/', PostUpdateView, name='update'),
    path('<int:post_pk>/delete/', PostDeleteView, name='delete'),

    # Likes
    path('likes/<int:post_id>/<str:slug>/', LikeView, name='likes'),
    # path('likes', LikeView, name='likes')
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogsproject/blogsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from django.conf import settings
from django.conf.urls.static import static
# UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blogs/', include("blogs.urls")),
    path('accounts/', include("accounts.urls")),
    # 인증
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/register/', UserCreateView.as_view(), name='register'),
    # path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# debug_toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ]

blogsproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}base_title{%endblock%}</title>
    {%block extrahead%}<link rel="stylesheet" href="{% static 'css/base.css' %}">{%endblock%}
</head>
<body>
    <div class="nav-bar">nav-bar</div>
    <div class="home-btn">
        <a href="{% url 'home' %}">Home</a>
        <a href="/admin">admin</a>
    </div>
    <ul>
        {% if user.is_active %}
        <div>
            {{user.username}}
            <a href="{% url 'accounts:logout' %}">Logout</a>
            <a href="{% url 'accounts:password_change' %}">Change Password</a>
        </div>
        {% else %}
        &ensp;Anonymous&ensp;
        <a href="{% url 'accounts:login' %}">Login</a>
        <a href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
    </ul>
    <a href="{% url 'blogs:add' %}">Add</a>
    <a href="{% url 'blogs:change' %}">Change</a>

    {%block content%}{%endblock%}
</body>
</html>

blogsproject/templates/home.html
{% extends 'base.html' %}
{%block title%}home_title{%endblock%}
{%load static%}
{%block extrahead%}{{block.super}}<link rel="stylesheet" href="{% static 'css/home.css' %}">{%endblock%}

{%block content%}
<h1>Home_page</h1>

{% for apps in app_list %}
<div class="apps">
    <a href="/{{apps}}" class="myapps1">{{apps}}</a>
    <div class="myapps2">2번앱</div>
    <div class="myapps3">3번앱</div>
</div>
{% endfor %}

{%endblock%}